# Translations template for designate.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the designate project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: designate 2015.2.0.dev68\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-05-28 06:04+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: designate/policy.py:100
#, python-format
msgid "Policy check succeeded for rule '%(rule)s' on target %(target)s"
msgstr ""

#: designate/policy.py:104
#, python-format
msgid "Policy check failed for rule '%(rule)s' on target %(target)s"
msgstr ""

#: designate/service.py:90
#, python-format
msgid "Starting %(name)s service (version: %(version)s)"
msgstr ""

#: designate/service.py:95
#, python-format
msgid "Stopping %(name)s service"
msgstr ""

#: designate/service.py:107
#, python-format
msgid "Creating RPC Server on topic '%s'"
msgstr ""

#: designate/service.py:123
#, python-format
msgid "Starting RPC server on topic '%s'"
msgstr ""

#: designate/service.py:204
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: designate/service.py:387
msgid "serve() can only be called once"
msgstr ""

#: designate/utils.py:439 designate/sqlalchemy/utils.py:68
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:30
msgid "An unknown exception occurred."
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:51
msgid "The service is unavailable"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:66
#, python-format
msgid "Infoblox backend is misconfigured: '%(option)s' must be defined."
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:71
#, python-format
msgid "Cannot search '%(objtype)s' object(s): %(content)s [code %(code)s]"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:76
#, python-format
msgid "Cannot create '%(objtype)s' object(s): %(content)s [code %(code)s]"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:81
#, python-format
msgid "Cannot delete object with ref %(ref)s: %(content)s [code %(code)s]"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:86
#, python-format
msgid "Cannot update object with ref %(ref)s: %(content)s [code %(code)s]"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:91
#, python-format
msgid ""
"Error occured during function's '%(func_name)s' call: ref %(ref)s: "
"%(content)s [code %(code)s]"
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:96
msgid "No Infoblox Member is available."
msgstr ""

#: designate/backend/impl_infoblox/ibexceptions.py:100
#, python-format
msgid "Infoblox object cannot be parsed from dict: %(data)s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:92
#, python-format
msgid "Issue happens during views creating: %s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:137
#, python-format
msgid "Infoblox %(obj_type)s already exists: %(ib_object)s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:145
#, python-format
msgid "Infoblox %(obj_type)s was created: %(ib_object)s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:164
#, python-format
msgid ""
"Infoblox %(obj_type)s will not be updated because it cannot be found: "
"%(payload)s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:181
#, python-format
msgid "Infoblox object was updated: %s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:185
#, python-format
msgid ""
"Infoblox %(obj_type)s will not be deleted because it cannot be found: "
"%(payload)s"
msgstr ""

#: designate/backend/impl_infoblox/object_manipulator.py:198
#, python-format
msgid "Infoblox object was deleted: %s"
msgstr ""

#: designate/cmd/manage.py:113
#, python-format
msgid "Could not read %s. Re-running with sudo"
msgstr ""

#: designate/cmd/manage.py:117
msgid "sudo failed, continuing as if nothing happened"
msgstr ""

#: designate/cmd/manage.py:119
msgid "Please re-run designate-manage as root."
msgstr ""

#: designate/manage/akamai.py:48
#, python-format
msgid "Failed to find target with ID %s"
msgstr ""

#: designate/manage/akamai.py:51
#, python-format
msgid "Found multiple targets with ID %s"
msgstr ""

#: designate/openstack/common/sslutils.py:53
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: designate/openstack/common/sslutils.py:56
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: designate/openstack/common/sslutils.py:59
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: designate/openstack/common/sslutils.py:62
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: designate/openstack/common/sslutils.py:105
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

